name: "GitSoviet Propaganda Generator"
description: "Render a propaganda poster from pull request metadata using OpenAI images."
author: "GitSoviet"
inputs:
  repo-name:
    description: "Repository in org/name form."
    required: true
  pr-title:
    description: "Title of the pull request."
    required: true
  pr-description:
    description: "Body/description of the pull request."
    required: false
    default: ""
  pr-author:
    description: "Username of the author."
    required: true
  diff:
    description: "Unified diff to feed into the prompt."
    required: true
  format:
    description: "poster or mural"
    required: false
    default: "poster"
  style:
    description: "soviet, dprk, cuban, capitalist, royalist"
    required: false
    default: "soviet"
  language:
    description: "Language for any slogans."
    required: false
    default: "English"
  additional-prompt:
    description: "Extra creative direction appended to the template."
    required: false
    default: ""
  provider:
    description: "Image provider (currently only openai)."
    required: false
    default: "openai"
  api-key:
    description: "API key for the image provider."
    required: true
  model:
    description: "Image generation model."
    required: false
    default: "gpt-image-1"
  size:
    description: "Image size (e.g. 1024x1024)."
    required: false
    default: ""
  output:
    description: "Output path for the generated poster."
    required: false
    default: "poster.png"
outputs:
  poster-path:
    description: "Path to the generated poster image."
    value: ${{ inputs.output }}
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - "--repo-name"
    - "${{ inputs.repo-name }}"
    - "--pr-title"
    - "${{ inputs.pr-title }}"
    - "--pr-description"
    - "${{ inputs.pr-description }}"
    - "--pr-author"
    - "${{ inputs.pr-author }}"
    - "--diff"
    - "${{ inputs.diff }}"
    - "--format"
    - "${{ inputs.format }}"
    - "--style"
    - "${{ inputs.style }}"
    - "--language"
    - "${{ inputs.language }}"
    - "--additional-prompt"
    - "${{ inputs['additional-prompt'] }}"
    - "--provider"
    - "${{ inputs.provider }}"
    - "--api-key"
    - "${{ inputs['api-key'] }}"
    - "--model"
    - "${{ inputs.model }}"
    - "--size"
    - "${{ inputs.size }}"
    - "--output"
    - "${{ inputs.output }}"

